### ISSUE TITLE
学习了~

### ISSUE THREAD

**Issue by 0x5e** [Big-Pi/UnicodeLog#1]
问几个问题哦
"\U"后面不一定是四位数字吧,是不是能用正则来替换什么的..
description那三个方法都需要替换的吗,只换descriptionWithLocale:indent:不可以吗
建议加上#if DEBUG,感觉这样会比较让人放心,毕竟release版本不能出差错

thanks~

**Comment by Big-Pi** [comment]
- CFStringTransform 转中文那段代码我也是从 stackOverflow 转载来的 ...  我对处理编码的问题也不是很了解 ...

- description 3个方法看起来是2个参数少的调用参数最多的 ... 不过我看不到它们的实现不敢确定 ... 记得只替换参数最多的那个方法时好像出现过小问题 ... 所以就写成现在这样了 ... 我会修改一下弄个分支自己测试看看 ... 

- 按你的建议已经加上 #if DEBUG 了 

ps : 谢谢你这么认真的看我代码并提出建议

**Comment by 0x5e** [comment]
😁
